### ISSUE TITLE
How to use it from the command line?

### ISSUE THREAD

**Issue by psprint** [remarkjs/remark-man#11]
How to use remark from the command-line? I'm looking for an alternative for the not developed `ronn` converter. Can be `remark` used in the same way?

**Comment by wooorm** [comment]
You asked for support [four minutes ago on Spectrum](https://spectrum.chat/unified/remark/how-to-use-remark-from-the-command-line~21e25220-d820-4b2e-a19a-137874794999). And I responded already.
